logging:
  level:
    springframework:
      jdbc:
        core:
          TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rladmlqls335
    url: jdbc:mysql://localhost:3306/sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

springdoc:
  swagger-ui:
    path: /swagger-ui.html
